language: node_js
node_js: stable
cache: yarn
script:
  - yarn
  - yarn run lint --no-fix && yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master